FROM python:3.10-slim

WORKDIR /beat

RUN apt-get update && apt-get install -y build-essential libpq-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# HuggingFace cache
ENV TRANSFORMERS_CACHE=/beat/hf_cache
RUN mkdir -p /beat/hf_cache

COPY . .

CMD ["celery", "-A", "app.workers.celery_app.celery_app", "beat", "--loglevel=info"]
