FROM python:3.10-slim

WORKDIR /trend_worker

# system packages
RUN apt-get update && apt-get install -y build-essential libpq-dev && apt-get clean

# HuggingFace cache (optional)
ENV TRANSFORMERS_CACHE=/trend_worker/hf_cache
RUN mkdir -p /trend_worker/hf_cache

# Install requirements
COPY requirements-prod.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy app
COPY . .

# Run Trend Worker
CMD ["python", "-m", "app.services.nlp.trend_worker"]
